name: Compile yaota8266.bin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: 'Set up Python v3'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: 'Init environment'
      env:
        PIPENV_NOSPIN: 1
      run: |
        make update
        make yaota8266-rsa-keys
        make assert-yaota8266-setup

    - name: 'Compile yaota8266.bin via docker'
      run: |
        make yaota8266-build
        ls -la build/
        file build/yaota8266.bin

