name: Compile MicroPython Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: 'Set up Python v3'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: 'Init environment'
      env:
        PIPENV_NOSPIN: 1
      run: |
        make update
        make yaota8266-rsa-keys
        cp docker-yaota8266/yaota8266/config.h.example docker-yaota8266/yaota8266/config.h

    - name: 'Compile MicroPython Firmware via docker'
      run: |
        make build-firmware
        ls -la build/
        file build/firmware-ota.bin
