name: Compile yaota8266.bin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 'Compile yaota8266.bin via docker'
      env:
        PIPENV_NOSPIN: 1
      run: |
        python3 -m pip install --upgrade pipenv
        make yaota8266-rsa-keys
        cp docker-yaota8266/yaota8266/config.h.example docker-yaota8266/yaota8266/config.h
        make yaota8266-compile
        ls -la build/
        file build/yaota8266.bin

