name: Compile MicroPython Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: 'Set up Python v3'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: 'Init environment'
      env:
        PIPENV_NOSPIN: 1
      run: |
        make update
        make yaota8266-rsa-keys

    - name: 'Compile MicroPython normal Firmware via docker'
      run: |
        make build-firmware-combined
        ls -la build/
        file build/firmware-combined.bin

    - name: 'Compile MicroPython OTA Firmware via docker'
      run: |
        make build-ota-firmware
        ls -la build/
        file build/firmware-ota.bin
        file build/firmware-ota.bin.ota
